import "../styles/main.scss";
import { Inter } from "next/font/google";
import Testing from "@/components/SetTime";
import Providers from "@/context/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "primary quiz",
  description: "Generated by collinz dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Providers>
        <body className={inter.className}>
          <Testing />
          {children}
        </body>
      </Providers>
    </html>
  );
}
